inherit_from: .rubocop_todo.yml

# !! のイディオムを許可
Style/DoubleNegation:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false
